name: ci-driver-prod
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/maratona-fc-1-part-5-driver
          tags: ${{ github.sha }}, latest
